id: ZhongkeWangwei-fileRead

info:
  name: Discuz论坛系统config_global.php.bak等备份文件信息泄露
  author: Str1am
  severity: high
  tags: Discuz,leakage

requests:
  - method: GET
    path:
      - "{{BaseURL}}/config/config_global.php.bak"
    matchers-condition: and
    matchers:
      - type: status
        status:
          - 200
      - type: word
        words:
          - "<?php"
          - "dbuser"
          - "dbpw"
        part: body
        condition: and
